/**
 * Hardcoded seed data for WCT v7.1.1 → v8.x migration mappings.
 * Loaded into SQLite on first boot if the DB is empty.
 */

export const KNOWN_PACKAGE_MAPPINGS = [
  { old: 'Microsoft.Toolkit.Uwp', new: 'CommunityToolkit.Uwp', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Controls', new: null, notes: 'Controls split into individual CommunityToolkit.Uwp.Controls.* packages. CommunityToolkit.Uwp.Controls meta-package does not exist in v8.', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', new: null, notes: 'DataGrid not ported to v8. Use standalone 7.x DataGrid package.', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Animations', new: 'CommunityToolkit.Uwp.Animations', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Behaviors', new: 'CommunityToolkit.Uwp.Behaviors', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Media', new: 'CommunityToolkit.Uwp.Media', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.Notifications', new: null, notes: 'Notifications not ported to CommunityToolkit.Uwp v8. Continue using Microsoft.Toolkit.Uwp.Notifications 7.x alongside v8 packages.', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.DeveloperTools', new: 'CommunityToolkit.Uwp.DeveloperTools', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.Connectivity', new: null, notes: 'Connectivity not ported to v8.', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI', new: 'CommunityToolkit.Uwp.Extensions', type: 'package' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Controls.Primitives', new: 'CommunityToolkit.Uwp.Controls.Primitives', type: 'package' },
];

// Namespace mapping for code transformations
export const NAMESPACE_MAPPINGS = [
  { old: 'Microsoft.Toolkit.Uwp.UI.Controls', new: 'CommunityToolkit.WinUI.Controls' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Animations', new: 'CommunityToolkit.WinUI.Animations' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Behaviors', new: 'CommunityToolkit.WinUI.Behaviors' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Media', new: 'CommunityToolkit.WinUI.Media' },
  { old: 'Microsoft.Toolkit.Uwp.Helpers', new: 'CommunityToolkit.WinUI.Helpers' },
  { old: 'Microsoft.Toolkit.Uwp.UI.Extensions', new: 'CommunityToolkit.WinUI' },
  { old: 'Microsoft.Toolkit.Uwp.Notifications', new: null },
];

export const KNOWN_API_MAPPINGS = [
  // Controls that moved to WinUI
  { old_api: 'Expander', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'Expander', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'Now built into WinUI. Use Microsoft.UI.Xaml.Controls.Expander directly.' },
  { old_api: 'NavigationView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'NavigationView', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'Built into WinUI.' },
  { old_api: 'RadialGradientBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'RadialGradientBrush', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Media', notes: 'Built into WinUI.' },
  { old_api: 'TabView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'TabView', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'Now built into WinUI.' },

  // Controls removed with replacement
  { old_api: 'AdaptiveGridView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_with_replacement', new_api: 'UniformGridLayout', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'Use ItemsRepeater with UniformGridLayout.', usage_example: '// XAML\nxmlns:muxc="using:Microsoft.UI.Xaml.Controls"\n\n<muxc:ItemsRepeater ItemsSource="{x:Bind Items}" ItemTemplate="{StaticResource MyTemplate}">\n  <muxc:ItemsRepeater.Layout>\n    <muxc:UniformGridLayout MinItemWidth="200" MinColumnSpacing="28" ItemsJustification="SpaceAround"/>\n  </muxc:ItemsRepeater.Layout>\n</muxc:ItemsRepeater>\n\n// C# code-behind\nusing Microsoft.UI.Xaml.Controls;\n\nvar repeater = new ItemsRepeater\n{\n    ItemsSource = Items,\n    Layout = new UniformGridLayout { MinItemWidth = 200, MinColumnSpacing = 28 }\n};', breaking_changes: 'Complete API change. AdaptiveGridView properties do not map 1:1.', reference_url: 'https://learn.microsoft.com/windows/apps/develop/ui/controls/items-repeater#change-the-layout-of-items' },
  { old_api: 'InAppNotification', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_with_replacement', new_api: 'StackedNotificationsBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Use StackedNotificationsBehavior with InfoBar.', usage_example: '// XAML\nxmlns:behaviors="using:CommunityToolkit.WinUI.Behaviors"\nxmlns:interactivity="using:Microsoft.Xaml.Interactivity"\nxmlns:muxc="using:Microsoft.UI.Xaml.Controls"\n\n<muxc:InfoBar>\n  <interactivity:Interaction.Behaviors>\n    <behaviors:StackedNotificationsBehavior x:Name="NotificationQueue"/>\n  </interactivity:Interaction.Behaviors>\n</muxc:InfoBar>\n\n// C# code-behind\nusing CommunityToolkit.WinUI.Behaviors;\nusing Microsoft.UI.Xaml.Controls;\n\nNotificationQueue.Show(new Notification\n{\n    Title = "Update available",\n    Message = "Restart to apply.",\n    Severity = InfoBarSeverity.Informational,\n});', breaking_changes: 'Different API surface. Use InfoBar + StackedNotificationsBehavior pattern.', reference_url: 'https://learn.microsoft.com/dotnet/communitytoolkit/windows/behaviors/stackednotificationsbehavior' },
  { old_api: 'DropShadowPanel', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_with_replacement', new_api: 'AttachedDropShadow', new_package: 'CommunityToolkit.Uwp.Extensions', new_namespace: 'CommunityToolkit.WinUI', notes: 'DropShadowPanel replaced by Attached Shadows. Use AttachedDropShadow for generic drop shadows (requires a CastTo sibling element as shadow target). Use AttachedCardShadow (CommunityToolkit.Uwp.Media) for card/rounded-rect shapes — simpler but Win2D dependency required.', usage_example: '// XAML — AttachedDropShadow (generic, requires sibling shadow target)\nxmlns:ui="using:CommunityToolkit.WinUI"\n\n<Grid>\n  <!-- Shadow target must be a sibling BEHIND the casting elements -->\n  <Border x:Name="ShadowTarget"/>\n  <Border Width="100" Height="100" CornerRadius="32">\n    <ui:Effects.Shadow>\n      <ui:AttachedDropShadow CastTo="{x:Bind ShadowTarget}" CornerRadius="32"/>\n    </ui:Effects.Shadow>\n  </Border>\n</Grid>\n\n// XAML — AttachedCardShadow alternative (no sibling needed, card shapes only)\nxmlns:ui="using:CommunityToolkit.WinUI"\nxmlns:media="using:CommunityToolkit.WinUI.Media"\n\n<Button Content="Shadowed">\n  <ui:Effects.Shadow>\n    <media:AttachedCardShadow Offset="4,4" BlurRadius="8"/>\n  </ui:Effects.Shadow>\n</Button>\n\n// C# code-behind — AttachedDropShadow\nusing CommunityToolkit.WinUI;\n\nEffects.SetShadow(myElement, new AttachedDropShadow { CastTo = shadowTarget, CornerRadius = 32 });\n\n// C# code-behind — AttachedCardShadow\nusing CommunityToolkit.WinUI;\nusing CommunityToolkit.WinUI.Media;\n\nEffects.SetShadow(myElement, new AttachedCardShadow { Offset = "4,4", BlurRadius = 8 });', breaking_changes: 'No panel wrapper to remove — attach shadow directly to the element via Effects.Shadow. AttachedDropShadow requires a designated sibling element as CastTo shadow target (cannot use parent). Remove the DropShadowPanel wrapper and apply shadow to the child element directly.', reference_url: 'https://learn.microsoft.com/dotnet/communitytoolkit/windows/extensions/attacheddropshadow' },
  { old_api: 'MarkdownTextBlock', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_with_replacement', new_api: 'MarkdownTextBlock', new_package: null, new_namespace: null, notes: 'Rewritten with Markdig parser in CommunityToolkit Labs. No stable NuGet package name verified for UWP. Check https://github.com/CommunityToolkit/Labs-Windows for the current Labs package.', reference_url: 'https://github.com/CommunityToolkit/Labs-Windows' },

  // Controls removed without replacement
  { old_api: 'DataGrid', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported. Continue using 7.x standalone package or use WinUI DataGrid from Gallery.' },

  // Direct renames (namespace change only)
  { old_api: 'BladeView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'BladeItem', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'CameraPreview', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'CameraPreview', new_package: 'CommunityToolkit.Uwp.Controls.CameraPreview', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'Carousel', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'DockPanel', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'GridSplitter', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'GridSplitter', new_package: 'CommunityToolkit.Uwp.Controls.Sizers', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Moved to dedicated Sizers package. API re-written but defaults are compatible.', usage_example: '// XAML\nxmlns:controls="using:CommunityToolkit.WinUI.Controls"\n\n<Grid>\n  <Grid.ColumnDefinitions>\n    <ColumnDefinition/>\n    <ColumnDefinition Width="16"/>\n    <ColumnDefinition/>\n  </Grid.ColumnDefinitions>\n  <!-- content col 0 -->\n  <controls:GridSplitter Grid.Column="1" Width="16"\n    HorizontalAlignment="Stretch"\n    ResizeBehavior="BasedOnAlignment"\n    ResizeDirection="Auto"/>\n  <!-- content col 2 -->\n</Grid>\n\n// C# code-behind\nusing CommunityToolkit.WinUI.Controls;\nusing Microsoft.UI.Xaml.Controls;\n\nvar splitter = new GridSplitter\n{\n    ResizeDirection = GridSplitter.GridResizeDirection.Columns,\n    ResizeBehavior = GridSplitter.GridResizeBehavior.BasedOnAlignment,\n};\nGrid.SetColumn(splitter, 1);', breaking_changes: 'Install CommunityToolkit.WinUI.Controls.Sizers instead of the generic Controls package.', reference_url: 'https://learn.microsoft.com/dotnet/communitytoolkit/windows/sizers/gridsplitter' },
  { old_api: 'HeaderedContentControl', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'HeaderedContentControl', new_package: 'CommunityToolkit.Uwp.Controls.HeaderedControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Moved to dedicated HeaderedControls package.' },
  { old_api: 'HeaderedItemsControl', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'HeaderedItemsControl', new_package: 'CommunityToolkit.Uwp.Controls.HeaderedControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Moved to dedicated HeaderedControls package.', breaking_changes: 'Orientation property removed. Customize ItemsPanel instead.' },
  { old_api: 'HeaderedTreeView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'HeaderedTreeView', new_package: 'CommunityToolkit.Uwp.Controls.HeaderedControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Moved to dedicated HeaderedControls package.' },
  { old_api: 'ImageCropper', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'ImageCropper', new_package: 'CommunityToolkit.Uwp.Controls.ImageCropper', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'ImageEx', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'LayoutTransformControl', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'LayoutTransformControl', new_package: 'CommunityToolkit.Uwp.Controls.LayoutTransformControl', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'Loading', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'MasterDetailsView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'Menu', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'MenuBar', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'Menu is now part of WinUI. Use MenuBar instead.', usage_example: '// XAML\nxmlns:muxc="using:Microsoft.UI.Xaml.Controls"\n\n<muxc:MenuBar>\n  <muxc:MenuBarItem Title="File">\n    <MenuFlyoutSubItem Text="New">\n      <MenuFlyoutItem Text="Plain Text Document"/>\n    </MenuFlyoutSubItem>\n    <MenuFlyoutItem Text="Open..."/>\n    <MenuFlyoutItem Text="Save"/>\n    <MenuFlyoutSeparator/>\n    <MenuFlyoutItem Text="Exit"/>\n  </muxc:MenuBarItem>\n  <muxc:MenuBarItem Title="Edit">\n    <MenuFlyoutItem Text="Undo"/>\n    <MenuFlyoutItem Text="Copy"/>\n    <MenuFlyoutItem Text="Paste"/>\n  </muxc:MenuBarItem>\n</muxc:MenuBar>\n\n// C# code-behind (add item handler)\nprivate void SaveItem_Click(object sender, RoutedEventArgs e)\n{\n    // handle save\n}', breaking_changes: 'Complete API change. Menu → MenuBar, MenuItem → MenuBarItem. Sub-items use MenuFlyoutItem/MenuFlyoutSubItem.', reference_url: 'https://learn.microsoft.com/windows/apps/develop/ui/controls/menus#create-a-menu-bar' },
  { old_api: 'MenuItem', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'moved_to_winui', new_api: 'MenuBarItem', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'MenuItem maps to WinUI MenuBarItem (top-level) or MenuFlyoutItem (sub-items).', breaking_changes: 'MenuItem → MenuBarItem for top-level items; sub-items use MenuFlyoutItem.', reference_url: 'https://learn.microsoft.com/windows/apps/develop/ui/controls/menus#create-a-menu-bar' },
  { old_api: 'MetadataControl', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'MetadataControl', new_package: 'CommunityToolkit.Uwp.Controls.MetadataControl', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'OrbitView', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'RadialGauge', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'RadialGauge', new_package: 'CommunityToolkit.Uwp.Controls.RadialGauge', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'RadialProgressBar', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_with_replacement', new_api: 'ProgressRing', new_package: 'Microsoft.UI.Xaml', new_namespace: 'Microsoft.UI.Xaml.Controls', notes: 'RadialProgressBar is deprecated in v8. Use WinUI ProgressRing. For indeterminate spinner use IsIndeterminate="True"; for determinate progress set IsIndeterminate="False" and bind Value (0-100).', usage_example: '// XAML — indeterminate spinner\n<ProgressRing IsIndeterminate="True" IsActive="True" Width="48" Height="48"/>\n\n// XAML — determinate (shows progress value)\n<ProgressRing IsIndeterminate="False" Value="{x:Bind Progress}" Width="48" Height="48"/>\n\n// C# code-behind\n// Indeterminate\nmyProgressRing.IsIndeterminate = true;\nmyProgressRing.IsActive = true;\n\n// Determinate\nmyProgressRing.IsIndeterminate = false;\nmyProgressRing.Value = 75; // 0–100\n\n// Stop\nmyProgressRing.IsActive = false;', breaking_changes: 'Complete API change. RadialProgressBar properties (Minimum, Maximum, Value, etc.) do not map to ProgressRing. ProgressRing.Value is always 0–100.', reference_url: 'https://learn.microsoft.com/windows/apps/develop/ui/controls/progress-controls' },
  { old_api: 'RotatorTile', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'ScrollHeader', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'StaggeredLayout', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'StaggeredPanel', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'TextToolbar', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'TileControl', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'TokenizingTextBox', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'direct_rename', new_api: 'TokenizingTextBox', new_package: 'CommunityToolkit.Uwp.Controls.TokenizingTextBox', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'Namespace changed.' },
  { old_api: 'UniformGrid', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },
  { old_api: 'WrapPanel', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to CommunityToolkit.Uwp v8. No replacement in stable v8 packages. Stay on 7.x for this control or check https://github.com/CommunityToolkit/Labs-Windows for experimental alternatives.' },

  // DataGrid types
  { old_api: 'DataGridColumn', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'DataGrid not ported to v8.' },
  { old_api: 'DataGridTextColumn', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'DataGrid not ported to v8.' },
  { old_api: 'DataGridCheckBoxColumn', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'DataGrid not ported to v8.' },
  { old_api: 'DataGridComboBoxColumn', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'DataGrid not ported to v8.' },
  { old_api: 'DataGridTemplateColumn', old_package: 'Microsoft.Toolkit.Uwp.UI.Controls.DataGrid', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'DataGrid not ported to v8.' },

  // Behaviors
  { old_api: 'ViewportBehavior', old_package: 'Microsoft.Toolkit.Uwp.UI.Behaviors', status: 'direct_rename', new_api: 'ViewportBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Namespace changed.' },
  { old_api: 'FocusBehavior', old_package: 'Microsoft.Toolkit.Uwp.UI.Behaviors', status: 'direct_rename', new_api: 'FocusBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Namespace changed.' },
  { old_api: 'AutoFocusBehavior', old_package: 'Microsoft.Toolkit.Uwp.UI.Behaviors', status: 'direct_rename', new_api: 'AutoFocusBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Namespace changed.' },
  { old_api: 'KeyDownTriggerBehavior', old_package: 'Microsoft.Toolkit.Uwp.UI.Behaviors', status: 'direct_rename', new_api: 'KeyDownTriggerBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Namespace changed.' },
  { old_api: 'StackedNotificationsBehavior', old_package: 'Microsoft.Toolkit.Uwp.UI.Behaviors', status: 'direct_rename', new_api: 'StackedNotificationsBehavior', new_package: 'CommunityToolkit.Uwp.Behaviors', new_namespace: 'CommunityToolkit.WinUI.Behaviors', notes: 'Namespace changed.' },

  // Media
  { old_api: 'BackdropBlurBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Media', status: 'direct_rename', new_api: 'BackdropBlurBrush', new_package: 'CommunityToolkit.Uwp.Media', new_namespace: 'CommunityToolkit.WinUI.Media', notes: 'Namespace changed.' },
  { old_api: 'BackdropGammaTransferBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Media', status: 'direct_rename', new_api: 'BackdropGammaTransferBrush', new_package: 'CommunityToolkit.Uwp.Media', new_namespace: 'CommunityToolkit.WinUI.Media', notes: 'Namespace changed.' },
  { old_api: 'BackdropInvertBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Media', status: 'direct_rename', new_api: 'BackdropInvertBrush', new_package: 'CommunityToolkit.Uwp.Media', new_namespace: 'CommunityToolkit.WinUI.Media', notes: 'Namespace changed.' },
  { old_api: 'BackdropSaturationBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Media', status: 'direct_rename', new_api: 'BackdropSaturationBrush', new_package: 'CommunityToolkit.Uwp.Media', new_namespace: 'CommunityToolkit.WinUI.Media', notes: 'Namespace changed.' },
  { old_api: 'BackdropSepiaBrush', old_package: 'Microsoft.Toolkit.Uwp.UI.Media', status: 'direct_rename', new_api: 'BackdropSepiaBrush', new_package: 'CommunityToolkit.Uwp.Media', new_namespace: 'CommunityToolkit.WinUI.Media', notes: 'Namespace changed.' },
  // Note: AttachedCardShadow was introduced in Microsoft.Toolkit.Uwp.UI.Media 7.1.2 (not 7.1.1).
  // Users on 7.1.1 would not have it. If migrating from 7.1.2, it's a simple namespace rename
  // to CommunityToolkit.WinUI.Media.AttachedCardShadow (no API changes).

  // Animations
  { old_api: 'AnimationBuilder', old_package: 'Microsoft.Toolkit.Uwp.UI.Animations', status: 'direct_rename', new_api: 'AnimationBuilder', new_package: 'CommunityToolkit.Uwp.Animations', new_namespace: 'CommunityToolkit.WinUI.Animations', notes: 'Namespace changed.' },
  { old_api: 'ImplicitAnimationSet', old_package: 'Microsoft.Toolkit.Uwp.UI.Animations', status: 'direct_rename', new_api: 'ImplicitAnimationSet', new_package: 'CommunityToolkit.Uwp.Animations', new_namespace: 'CommunityToolkit.WinUI.Animations', notes: 'Namespace changed.' },
  { old_api: 'ExplicitAnimationSet', old_package: 'Microsoft.Toolkit.Uwp.UI.Animations', status: 'direct_rename', new_api: 'ExplicitAnimationSet', new_package: 'CommunityToolkit.Uwp.Animations', new_namespace: 'CommunityToolkit.WinUI.Animations', notes: 'Namespace changed.' },

  // Notifications
  { old_api: 'ToastContentBuilder', old_package: 'Microsoft.Toolkit.Uwp.Notifications', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'CommunityToolkit.Uwp.Notifications does not exist in v8. Continue using Microsoft.Toolkit.Uwp.Notifications 7.x alongside v8 packages, or use Windows.UI.Notifications WinRT API directly.' },
  { old_api: 'TileContentBuilder', old_package: 'Microsoft.Toolkit.Uwp.Notifications', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to v8. Continue using Microsoft.Toolkit.Uwp.Notifications 7.x.' },
  { old_api: 'BadgeContentBuilder', old_package: 'Microsoft.Toolkit.Uwp.Notifications', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'Not ported to v8. Continue using Microsoft.Toolkit.Uwp.Notifications 7.x.' },

  // Developer Tools
  { old_api: 'AlignmentGrid', old_package: 'Microsoft.Toolkit.Uwp.DeveloperTools', status: 'direct_rename', new_api: 'AlignmentGrid', new_package: 'CommunityToolkit.Uwp.DeveloperTools', new_namespace: 'CommunityToolkit.WinUI.DeveloperTools', notes: 'Namespace changed.' },
  { old_api: 'FocusTracker', old_package: 'Microsoft.Toolkit.Uwp.DeveloperTools', status: 'direct_rename', new_api: 'FocusTracker', new_package: 'CommunityToolkit.Uwp.DeveloperTools', new_namespace: 'CommunityToolkit.WinUI.DeveloperTools', notes: 'Namespace changed.' },

  // Connectivity
  { old_api: 'BluetoothLEHelper', old_package: 'Microsoft.Toolkit.Uwp.Connectivity', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'CommunityToolkit.Uwp.Connectivity does not exist in v8. The Connectivity component was not ported.' },
  { old_api: 'NetworkHelper', old_package: 'Microsoft.Toolkit.Uwp.Connectivity', status: 'removed_no_replacement', new_api: null, new_package: null, new_namespace: null, notes: 'CommunityToolkit.Uwp.Connectivity does not exist in v8. The Connectivity component was not ported.' },

  // New in v8
  { old_api: null, old_package: null, status: 'new_in_v8', new_api: 'SettingsCard', new_package: 'CommunityToolkit.Uwp.Controls.SettingsControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'New in v8. UWP package: CommunityToolkit.Uwp.Controls.SettingsControls (8.3.x preview as of stable v8; check NuGet for current release).' },
  { old_api: null, old_package: null, status: 'new_in_v8', new_api: 'SettingsExpander', new_package: 'CommunityToolkit.Uwp.Controls.SettingsControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'New in v8. UWP package: CommunityToolkit.Uwp.Controls.SettingsControls (8.3.x preview as of stable v8).' },
  { old_api: null, old_package: null, status: 'new_in_v8', new_api: 'Segmented', new_package: 'CommunityToolkit.Uwp.Controls.SettingsControls', new_namespace: 'CommunityToolkit.WinUI.Controls', notes: 'New in v8. UWP package: CommunityToolkit.Uwp.Controls.SettingsControls (8.3.x preview as of stable v8).' },
];
